const DB='mamina-v1', VERSION=2
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('kv'))db.createObjectStore('kv');if(!db.objectStoreNames.contains('messages')){const s=db.createObjectStore('messages',{keyPath:'key'});s.createIndex('topic','topic')}if(!db.objectStoreNames.contains('files'))db.createObjectStore('files')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
export const kv={
  async get(k){const db=await openDb();try{return await new Promise((res,rej)=>{const r=db.transaction('kv').objectStore('kv').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}finally{db.close()}},
  async set(k,v){const db=await openDb();try{await new Promise((res,rej)=>{const t=db.transaction('kv','readwrite');t.objectStore('kv').put(v,k);t.oncomplete=res;t.onerror=()=>rej(t.error)})}finally{db.close()}},
  async del(k){const db=await openDb();try{await new Promise((res,rej)=>{const t=db.transaction('kv','readwrite');t.objectStore('kv').delete(k);t.oncomplete=res;t.onerror=()=>rej(t.error)})}finally{db.close()}},
}
export async function cacheMessages(topicKey, rows){const db=await openDb();try{await new Promise((res,rej)=>{const t=db.transaction('messages','readwrite'),s=t.objectStore('messages');for(const row of rows)s.put({...row,key:`${topicKey}:${row.id}`,topic:topicKey});t.oncomplete=res;t.onerror=()=>rej(t.error)})}finally{db.close()}}
export async function getCachedMessages(topicKey){const db=await openDb();try{return await new Promise((res,rej)=>{const r=db.transaction('messages').objectStore('messages').index('topic').getAll(topicKey);r.onsuccess=()=>res((r.result||[]).sort((a,b)=>a.id-b.id));r.onerror=()=>rej(r.error)})}finally{db.close()}}
export async function clearTopicCache(topicKey){const rows=await getCachedMessages(topicKey),db=await openDb();try{await new Promise((res,rej)=>{const t=db.transaction('messages','readwrite'),s=t.objectStore('messages');for(const r of rows)s.delete(r.key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}finally{db.close()}}
export async function putFile(key, bytes){const db=await openDb();try{await new Promise((res,rej)=>{const t=db.transaction('files','readwrite');t.objectStore('files').put(bytes,key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}finally{db.close()}}
export async function getFile(key){const db=await openDb();try{return await new Promise((res,rej)=>{const r=db.transaction('files').objectStore('files').get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}finally{db.close()}}
