import {TelegramClient,InputMedia} from '@mtcute/web'
import {TELEGRAM_CONFIG} from './config.js'
import './style.css'
const $=id=>document.getElementById(id)
const LAST='mamina:last-dialog',CUR='mamina:cursor:',DB='mamina-cache',STORE='messages'
let tg=null,dialogs=[],selectedDialog=null,currentUser=null,replyTargetId=null,uploadLimitBytes=null
const status=(id,t,ok=null)=>{const e=$(id);e.textContent=t;e.className='status'+(ok===true?' ok':ok===false?' error':'')}
const debug=v=>$('debug').textContent+=($('debug').textContent?'\n':'')+(typeof v==='string'?v:JSON.stringify(v,(k,x)=>typeof x==='bigint'?x.toString():x,2))
const peerId=p=>String(typeof p?.id==='bigint'?p.id:p?.id?.value??p?.id??'')
const peerName=p=>p?.displayName||p?.title||p?.username||p?.firstName||'(sans nom)'
const senderName=m=>m?.sender?.displayName||m?.sender?.username||m?.sender?.firstName||'—'
function client(){if(!tg)tg=new TelegramClient({apiId:TELEGRAM_CONFIG.apiId,apiHash:TELEGRAM_CONFIG.apiHash,storage:'mamina-telegram-user',logLevel:2});return tg}
async function login(){const c=client();currentUser=await c.start({phone:async()=>prompt('Numéro Telegram (+33…)')||'',code:async()=>prompt('Code reçu')||'',password:async()=>prompt('Mot de passe 2FA')||''});status('loginStatus',`Connecté : ${currentUser.displayName||''}`,true);await loadLimit(c);return c}
async function loadLimit(c){try{let cfg=null;if(c.appConfig&&typeof c.appConfig.get==='function'){cfg={upload_max_fileparts_default:await c.appConfig.get('upload_max_fileparts_default'),upload_max_fileparts_premium:await c.appConfig.get('upload_max_fileparts_premium')}}if(!cfg?.upload_max_fileparts_default)cfg=decode(await c.call({_: 'help.getAppConfig',hash:0}));const n=Number(cfg?.upload_max_fileparts_default||0),p=Number(cfg?.upload_max_fileparts_premium||0),parts=(currentUser?.premium&&p)||n;uploadLimitBytes=parts?parts*524288:null;status('limitStatus',uploadLimitBytes?`Limite détectée : ${fmt(uploadLimitBytes)} (${currentUser?.premium?'Premium':'standard'})`:'Limite non déterminée.',!!uploadLimitBytes)}catch(e){debug(e.message);status('limitStatus','Limite non déterminée.',false)}}
function decode(v){if(v==null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(decode);const t=String(v._||'').toLowerCase();if(t.includes('jsonnull'))return null;if(t.includes('jsonbool')||t.includes('jsonnumber')||t.includes('jsonstring'))return v.value;if(t.includes('jsonarray'))return (v.value||[]).map(decode);if(t.includes('jsonobject')){const o={};for(const x of v.value||[])o[x.key]=decode(x.value);return o}for(const k in v){const d=decode(v[k]);if(d&&typeof d==='object'&&('upload_max_fileparts_default'in d||'upload_max_fileparts_premium'in d))return d}return v}
$('connect').onclick=async()=>{try{await login()}catch(e){status('loginStatus','Erreur : '+e.message,false)}}
$('logout').onclick=async()=>{try{await client().logOut();tg=null;status('loginStatus','Session révoquée.',true)}catch(e){status('loginStatus','Erreur : '+e.message,false)}}
$('loadDialogs').onclick=async()=>{try{const c=await login();dialogs=[];for await(const d of c.iterDialogs({limit:200}))dialogs.push(d);const s=$('dialogSelect');s.innerHTML='<option value="">— choisir —</option>';const last=localStorage.getItem(LAST);dialogs.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${peerName(d.peer)} · ${peerId(d.peer)}`;if(last===peerId(d.peer))o.selected=true;s.appendChild(o)});if(s.value!==''){selectedDialog=dialogs[+s.value];await selected()}status('dialogStatus',`${dialogs.length} dialog(s)`,true)}catch(e){status('dialogStatus','Erreur : '+e.message,false)}}
$('dialogSelect').onchange=async()=>{selectedDialog=$('dialogSelect').value===''?null:dialogs[+$('dialogSelect').value];if(selectedDialog)await selected()}
async function selected(){localStorage.setItem(LAST,peerId(selectedDialog.peer));status('dialogStatus',`Sélectionné : ${peerName(selectedDialog.peer)}`,true);$('topicSelect').innerHTML='<option value="">— discussion générale —</option>';renderCursor();await renderCache()}
function reqPeer(){if(!selectedDialog?.peer)throw new Error('Choisis un dialog.');return selectedDialog.peer}
$('createTopic').onclick=async()=>{try{const title=$('topicTitle').value.trim();if(!title)throw new Error('Titre manquant.');const m=await (await login()).createForumTopic({chatId:reqPeer(),title});const tid=Number(m?.replyToMessage?.threadId||m?.threadId||m?.id);const o=document.createElement('option');o.value=tid;o.textContent=`${title} · ${tid}`;$('topicSelect').appendChild(o);$('topicSelect').value=tid;status('topicStatus',`Sujet créé : ${title}`,true);$('topicTitle').value=''}catch(e){status('topicStatus','Erreur : '+e.message,false)}}
$('file').onchange=()=>{const f=$('file').files?.[0];$('preview').style.display='none';$('fileInfo').textContent='';if(!f)return;$('fileInfo').textContent=`${f.name} · ${fmt(f.size)} · ${f.type||'type inconnu'}`;if(f.type.startsWith('image/')){$('preview').src=URL.createObjectURL(f);$('preview').style.display='block'}if(uploadLimitBytes&&f.size>uploadLimitBytes)status('sendStatus',`Trop volumineux : ${fmt(f.size)} > ${fmt(uploadLimitBytes)}`,false)}
function fmt(b){const u=['o','Ko','Mo','Go','To'];let n=+b,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toLocaleString('fr-FR',{maximumFractionDigits:i?1:0})} ${u[i]}`}
const threadId=()=>$('topicSelect').value?+$('topicSelect').value:undefined
function clearReply(){replyTargetId=null;$('replyBox').hidden=true}
$('cancelReply').onclick=clearReply
$('send').onclick=async()=>{const btn=$('send');try{const c=await login(),peer=reqPeer(),text=$('text').value.trim(),file=$('file').files?.[0];if(!text&&!file)throw new Error('Ajoute texte et/ou fichier.');if(file&&uploadLimitBytes&&file.size>uploadLimitBytes)throw new Error('Fichier trop volumineux.');btn.disabled=true;const common={threadId:threadId(),replyTo:replyTargetId||undefined};let sent;if(file){$('uploadWrap').hidden=false;const media=file.type.startsWith('image/')?InputMedia.photo(file):{type:'document',file,fileName:file.name,fileMime:file.type||'application/octet-stream',fileSize:file.size};sent=await c.sendMedia(peer,media,{...common,caption:text||undefined,progressCallback:(u,t)=>{const p=t?Math.round(u/t*100):0;$('uploadProgress').value=p;$('uploadText').textContent=p+' %'}})}else sent=await c.sendText(peer,text,common);status('sendStatus',`Publié ✓ #${sent.id}`,true);$('text').value='';$('file').value='';$('preview').style.display='none';$('fileInfo').textContent='';$('uploadWrap').hidden=true;clearReply()}catch(e){status('sendStatus','Erreur : '+e.message,false)}finally{btn.disabled=false}}
const ckey=()=>CUR+peerId(reqPeer()),cursor=()=>+(localStorage.getItem(ckey())||0),setCursor=x=>localStorage.setItem(ckey(),x),renderCursor=()=>status('syncStatus',cursor()?`Dernier message synchronisé : #${cursor()}`:'Aucune synchronisation précédente.')
const textOf=m=>m?.text||m?.caption||m?.message||'',hasMedia=m=>!!(m?.media||m?.photo||m?.document||m?.video||m?.animation)
async function parentInfo(c,m){try{const p=await c.getReplyTo(m);return p?{id:+p.id,author:senderName(p),text:textOf(p).slice(0,160)}:null}catch{return null}}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'key'});s.createIndex('dialogId','dialogId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(x){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(x);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}
async function rows(id){const db=await openDb();const a=await new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).index('dialogId').getAll(id);q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)});db.close();return a.sort((a,b)=>a.id-b.id)}
async function clearRows(id){const a=await rows(id),db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const r of a)s.delete(r.key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}
function serial(m,p){const d=peerId(reqPeer());return{key:`${d}:${+m.id}`,dialogId:d,id:+m.id,author:senderName(m),date:m.date?new Date(m.date).toISOString():null,text:textOf(m),hasMedia:hasMedia(m),parent:p,threadId:+(m.threadId||m.topicId||m.replyToMessage?.threadId||0)||null}}
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;")
async function renderCache(){if(!selectedDialog)return;const a=await rows(peerId(reqPeer())),c=$('messages');c.innerHTML='';if(!a.length){c.innerHTML='<p class="hint">Cache vide.</p>';return}for(const x of a){const b=document.createElement('article');b.className='message';b.innerHTML=`<div class="message-meta"><b>${esc(x.author)}</b><span class="badge">#${x.id}</span>${x.threadId?`<span class="badge">topic ${x.threadId}</span>`:''}</div>${x.parent?`<div class="reply-preview">↳ réponse à #${x.parent.id} · ${esc(x.parent.author)}<br>${esc(x.parent.text||'')}</div>`:''}<div>${esc(x.text||'')}</div>${x.hasMedia?'<div>📎 média</div>':''}<div class="action-row"><button class="reply-action" data-id="${x.id}" data-p="${esc((x.text||'').slice(0,100))}">Répondre</button></div>`;c.appendChild(b)}c.querySelectorAll('.reply-action').forEach(btn=>btn.onclick=()=>{replyTargetId=+btn.dataset.id;$('replyId').textContent=replyTargetId;$('replyPreview').textContent=btn.dataset.p;$('replyBox').hidden=false;$('text').focus()})}
$('sync').onclick=async()=>{const btn=$('sync');try{const c=await login(),peer=reqPeer(),prev=cursor(),msgs=[];btn.disabled=true;if(!prev)msgs.push(...Array.from(await c.getHistory(peer,{limit:50})));else for await(const m of c.iterHistory(peer,{minId:prev,limit:Infinity}))if(+m.id>prev)msgs.push(m);msgs.sort((a,b)=>+a.id-+b.id);for(const m of msgs)await put(serial(m,await parentInfo(c,m)));if(msgs.length)setCursor(Math.max(...msgs.map(m=>+m.id)));status('syncStatus',msgs.length?`${msgs.length} nouveau(x) message(s).`:`Aucun nouveau message depuis #${prev}.`,true);await renderCache()}catch(e){status('syncStatus','Erreur : '+e.message,false)}finally{btn.disabled=false}}
$('clearCache').onclick=async()=>{try{await clearRows(peerId(reqPeer()));localStorage.removeItem(ckey());renderCursor();await renderCache()}catch(e){status('syncStatus','Erreur : '+e.message,false)}}
window.addEventListener('load',()=>{if(TELEGRAM_CONFIG.apiId===12345678)status('loginStatus','Configuration factice : remplace src/config.js.',false)})
